### ISSUE TITLE
core.logger and core.metrics is missing

### ISSUE THREAD

**Issue by ghost** [AXNing/KSID#1]
No 'core' folder in this repo. Error happens here:
https://github.com/AXNing/KSID/blob/cc2489d084dbfadbf0a4e1b092c99b270e3b3e0b/test.py#L22

Found this though:

https://github.com/bycloudai/ISRIR-colab/tree/master/core

https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/tree/master/core

**Comment by duang1412** [comment]
Did you run it successfully after adding the core folder?

**Comment by ghost** [comment]
Yes the one from `ISRIR-colab` seems to work. I was able to run test.py fully with LOLv1 dataset.

Here is my Kaggle notebook: https://www.kaggle.com/code/funtain32/kan-see-in-the-dark

Also had to fix a couple things:
- Can't find module: `sed -i 's/from k_an import kan/from model.ddpm_modules.k_an import kan/' model/ddpm_modules/unet.py`
- Deleting this line and the next: `!sed -i "/if phase == 'train'/,+1d" core/logger.py`
- Missing resume_state in config: `!sed -i 's/"resume_state": ""/"resume_state": "checkpoints/LOLv1_gen.pth"/' config/lolv1_test.json`

**Comment by AXNing** [comment]
> 是的，来自 的那个似乎有效。我能够使用 LOLv1 数据集完全运行 test.py。`ISRIR-colab`
> 
> 这是我的 Kaggle 笔记本：https://www.kaggle.com/code/funtain32/kan-see-in-the-dark
> 
> 还必须修复几件事：
> 
> * 找不到模块：`sed -i 's/from k_an import kan/from model.ddpm_modules.k_an import kan/' model/ddpm_modules/unet.py`
> * 删除此行和下一行：`!sed -i "/if phase == 'train'/,+1d" core/logger.py`
> * 配置中缺少 resume_state：`!sed -i 's/"resume_state": ""/"resume_state": "checkpoints/LOLv1_gen.pth"/' config/lolv1_test.json`

Thank you for your suggestion, we will improve the code as soon as possible.

**Comment by AXNing** [comment]
We have improved the relevant testing code, if there is any problem, please point out, thank you!
